#!/usr/bin/env php
<?php
// Load the configuration file which contains the current configuration and load the yii related files
$config = require __DIR__ . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);